apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-processor
  namespace: stepflow
  labels:
    app: ai-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-processor
  template:
    metadata:
      labels:
        app: ai-processor
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: ai-processor
        image: stepflow/ai-processor:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: "redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: stepflow-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: stepflow-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stepflow-secrets
              key: redis-password
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: stepflow-config
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: stepflow-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: stepflow-secrets
              key: aws-secret-access-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: stepflow-secrets
              key: openai-api-key
        - name: ELEVENLABS_API_KEY
          valueFrom:
            secretKeyRef:
              name: stepflow-secrets
              key: elevenlabs-api-key
        livenessProbe:
          exec:
            command:
            - python
            - health_check.py
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - python
            - health_check.py
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-processor-service
  namespace: stepflow
spec:
  selector:
    app: ai-processor
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-processor-hpa
  namespace: stepflow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-processor
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85